// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Forge")>]
[<assembly: AssemblyProductAttribute("Forge")>]
[<assembly: AssemblyDescriptionAttribute("Forge is a build tool that provides tasks for creating, compiling, and testing F# projects")>]
[<assembly: AssemblyVersionAttribute("2.2.0")>]
[<assembly: AssemblyFileVersionAttribute("2.2.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Forge"
    let [<Literal>] AssemblyProduct = "Forge"
    let [<Literal>] AssemblyDescription = "Forge is a build tool that provides tasks for creating, compiling, and testing F# projects"
    let [<Literal>] AssemblyVersion = "2.2.0"
    let [<Literal>] AssemblyFileVersion = "2.2.0"
